name: Build Yocto

on:
  workflow_call:
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.create-output.outputs.url }}

env:
  BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
  CACHE_DIR: /srv/gh-runners/quic-yocto
  KAS_REPO_REF_DIR: /srv/gh-runners/quic-yocto/kas-mirrors
  BASE_ARTIFACT_URL: https://quic-yocto-fileserver-1029608027416.us-central1.run.app

jobs:
  kas-mirror:
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - name: Update kas mirrors
        run: |
          for r in $(find ${KAS_REPO_REF_DIR}/* -maxdepth 0 -type d); do
            echo "pre-fetch: $r"
            git -C $r fetch --prune origin '+refs/*:refs/*'
          done

  kas-lock:
    needs:  kas-mirror
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run kas lock
        run: |
          kas dump --update --lock --inplace ci/base.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-check-layer:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          ci/yocto-check-layer.sh

  yocto-patchreview:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run Yocto patchreview
        run: |
          ci/yocto-patchreview.sh

  compile:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/meta-qcom'
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - qcs9100-ride-sx
          - qrb2210-rb1-core-kit
          - qcom-armv8a
          - qcom-armv7a
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Kas build
        run: |
          export DL_DIR=${CACHE_DIR}/downloads
          export SSTATE_DIR=${CACHE_DIR}/sstate-cache
          export KAS_WORK_DIR=$PWD/../kas
          mkdir $KAS_WORK_DIR
          kas build ci/mirror.yml:ci/${{ matrix.machine }}.yml
          ci/yocto-pybootchartgui.sh && mv $KAS_WORK_DIR/build/buildchart.svg .

      - uses: actions/upload-artifact@v4
        with:
          name: buildchart-${{ matrix.machine }}
          path: buildchart.svg

      - name: Publish image for LAVA
        env:
          TOKEN: ${{ secrets.FIO_FILESERVER_TOKEN }}
        run: |
          set -e
          set -o pipefail

          if [ -z "${TOKEN}" ] ; then
              echo "ERROR: Missing FIO_FILESERVER_TOKEN"
              exit 1
          fi
          cd ../kas/build/tmp/deploy/images/${{matrix.machine}}

          file=$(find ./ -type f -name \*qcomflash.tar.gz\* | head -n1 | sed 's/.\///')
          if [ -z "$file" ] ; then
              echo "No file found for LAVA"
              exit 0
          fi

          echo "Found ${file}"
          url=$(curl -v -w '%header{location}' -X PUT -H "Authentication: token ${TOKEN}" \
                ${BASE_ARTIFACT_URL}/${BUILD_ID}/${{ matrix.machine }}/${file})
          echo "Uploading to ${url}"

          curl -v -X PUT --progress-bar -H "Content-Type: application/octet-stream" --upload-file ${file} "${url}" | cat

      - name: Publish image
        run: |
          build_dir=${CACHE_DIR}/builds/${BUILD_ID}
          mkdir -p $build_dir
          img_dir=$build_dir/${{ matrix.machine }}
          [ -d $img_dir ] && rm -rf $img_dir
          deploy_dir=../kas/build/tmp/deploy/images/${{matrix.machine}}
          find $deploy_dir/ -maxdepth 1 -name "*.rootfs*.qcomflash" -exec rm -rf {} \;
          mv $deploy_dir $img_dir

          # Instruct our file server to make these files available for download
          url="${BASE_ARTIFACT_URL}/${BUILD_ID}/${{ matrix.machine }}/"

          retries=8
          okay=0
          shopt -s lastpipe  # allows us to capture the value of `okay` in the while loop below
          for ((i=0; i<retries; i++)); do
              curl -X POST -H "Accept: text/event-stream" -i --fail-with-body -s -N ${url} | \
                  while read line; do
                      echo $line
                      if [[ $line == STATUS=* ]]; then
                          if [[ $line == "STATUS=OK" ]]; then
                              okay=1
                              break
                          fi
                      fi
                  done
              [ $okay -eq 1 ] && break
              echo # new line break in case response doesn't have one
              echo "Error: unable to publish artifacts, sleep and retry"
              sleep 2
          done
          (( retries == i )) && { echo 'Failed to publish artifacts'; exit 1; }

          echo # new line break in case response doesn't have one
          echo Image available at: ${url}

  create-output:
    needs: compile
    outputs:
      url: ${{ steps.print-output.outputs.url }}
    runs-on: [self-hosted, x86]
    steps:
      - name: "Print output"
        id: print-output
        run: |
          build_url="${BASE_ARTIFACT_URL}/${BUILD_ID}"
          echo "Downloads URL: ${build_url}"
          echo "url=\"${build_url}\"" >> $GITHUB_OUTPUT
          echo "${build_url}" > build_url
      - name: Upload build URL
        uses: actions/upload-artifact@v4
        with:
          name: build_url
          path: build_url
