name: Build Yocto

on:
  workflow_call:
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.create-output.outputs.url }}

env:
  CACHE_DIR: /efs/qli/metaqcom/gh-runners/quic-yocto
  KAS_REPO_REF_DIR: ${CACHE_DIR}/kas-mirrors
  BASE_ARTIFACT_URL: "https://artifactory-qdc-global.qualcomm.com/artifactory/pdlm-qcomlinux-generic-lv-fed/QualcommLinuxPrd/qualcomm-linux/meta-qcom/${{ github.run_id }}"

jobs:
  kas-mirror:
    if: github.repository == 'qualcomm-linux/awstest-meta-qcom'
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Update kas mirrors
        run: |
          for r in $(find ${KAS_REPO_REF_DIR}/* -maxdepth 0 -type d); do
            echo "pre-fetch: $r"
            git -C $r fetch --prune origin '+refs/*:refs/*'
          done

  kas-lock:
    needs:  kas-mirror
    if: github.repository == 'qualcomm-linux/awstest-meta-qcom'
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run kas lock
        run: |
          sudo -E -u builder kas dump --update --lock --inplace ci/base.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-check-layer:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/awstest-meta-qcom'
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          sudo -E -u builder ci/yocto-check-layer.sh

  yocto-patchreview:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/awstest-meta-qcom'
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run Yocto patchreview
        run: |
          ci/yocto-patchreview.sh

  compile:
    needs: kas-lock
    if: github.repository == 'qualcomm-linux/awstest-meta-qcom'
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true  # This tells our self-hosted runner to upload artifacts
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - qcs9100-ride-sx
          - qrb2210-rb1-core-kit
          - qcom-armv8a
          - qcom-armv7a
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Kas build
        run: |
          export DL_DIR=${CACHE_DIR}/downloads
          export SSTATE_DIR=${CACHE_DIR}/sstate-cache
          export KAS_WORK_DIR=$PWD/../kas
          mkdir $KAS_WORK_DIR
          sudo -E -u builder kas build ci/mirror.yml:ci/${{ matrix.machine }}.yml

      - name: Publish image
        run: |
          build_dir=${CACHE_DIR}/builds/${GITHUB_RUN_ID}
          mkdir -p $build_dir
          img_dir=$build_dir/${{ matrix.machine }}
          [ -d $img_dir ] && rm -rf $img_dir
          deploy_dir=../kas/build/tmp/deploy/images/${{matrix.machine}}
          find $deploy_dir/ -maxdepth 1 -name "*.rootfs*.qcomflash" -exec rm -rf {} \;
          mv $deploy_dir $img_dir

          url="${BASE_ARTIFACT_URL}/${{ matrix.machine }}/"
          echo Image available at: ${url}

  create-output:
    needs: compile
    outputs:
      url: ${{ steps.print-output.outputs.url }}
    runs-on:
      - codebuild-QualcommLinux-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: "Print output"
        id: print-output
        run: |
          echo "Downloads URL: ${BASE_ARTIFACT_URL}"
          echo "url=\"${BASE_ARTIFACT_URL}\"" >> $GITHUB_OUTPUT
          echo "${BASE_ARTIFACT_URL}" > build_url
      - name: Upload build URL
        uses: actions/upload-artifact@v4
        with:
          name: build_url
          path: build_url
