name: Build on PR

on:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read
  security-events: read

env:
  BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
  BASE_ARTIFACT_URL: https://quic-yocto-fileserver-1029608027416.us-central1.run.app

jobs:
  andy:
    runs-on: [self-hosted, x86]
    steps:
      - name: andy
        run: |
          set -e
          set -o pipefail
          file=tmp.txt
          echo "ANDY TEST" > $file
          echo "Found ${file}"
          url=$(curl -w '%{redirect_url}' -X PUT -H "Authentication: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                ${BASE_ARTIFACT_URL}/${BUILD_ID}/andy/${file})
          echo "Uploading to ${url}"

          curl -v -X PUT --progress-bar -H "Content-Type: application/octet-stream" --upload-file ${file} "${url}" | cat
